services:
  web:
    image: marcobejarano/rk8s-py:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "marcobejarano/rk8s-py:${TAG:-latest}"  
    container_name: "rk8s-py-${TAG:-latest}"
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - mywebdata:/app/data
    networks:
      - python_network

volumes:
  mywebdata:
    name: mywebdata
    
networks:
  python_network:
    driver: bridge
    name: python_network
