services:
  web:
    restart: always
    image: marcobejarano/rk8s-py:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "marcobejarano/rk8s-py:${TAG:-latest}"  
    container_name: "rk8s-py-${TAG:-latest}"
    ports:
      - "80:8080"
    environment:
      - PORT=8080
    env_file:
      - .env
    volumes:
      - mywebdata:/app/data
    networks:
      - python_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mywebdata:
    name: mywebdata
    
networks:
  python_network:
    driver: bridge
    name: python_network
