name: Compose - Build, Push & Deploy
on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-24.04
    env:
      DH_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      REPO: ${{ secrets.DOCKERHUB_REPO }}
      SSH_OPTS: "-o StrictHostKeyChecking=no"
      REMOTE: "root@${{ secrets. AKAMAI_INSTANCE_IP_ADDRESS }}"
      REMOTE_APP_DIR: "/opt/app"
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build the Docker Image
        run: |
          docker build \
          -t "$DH_USER/$REPO:latest" \
          -t "$DH_USER/$REPO:${{ github.sha }}" \
          .
          
      - name: Push the Docker Image to Docker Hub
        run: |
          docker push "$DH_USER/$REPO" --all-tags
