name: Build and Push Image
on:
  workflow_dispatch:
  
jobs:
  build-push:
    runs-on: ubuntu-24.04
    env:
      DH_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      REPO: ${{ secrets.DOCKERHUB_REPO }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build the Container
        run: |
          docker build \
          -t "$DH_USER/$REPO:latest" \
          -t "$DH_USER/$REPO:${{ github.sha }}" \
          .
          
      - name: Push the Container Images
        run: |
          docker push "$DH_USER/$REPO" --all-tags
